
networks:
  gitea-network:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__database__SSL_MODE=disable
      - GITEA__cors__ENABLED=true
      - GITEA__cors__ALLOW_ORIGIN=http://localhost:8080
      - GITEA__cors__ALLOW_CREDENTIALS=true
      - GITEA__cors__ALLOW_HEADERS=Authorization, Content-Type
      - GITEA__server__ROOT_URL=http://localhost:3000/
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__session__PROVIDER=file
      - GITEA__security__INTERNAL_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NDE3MDYzMDd9.UfJxCwucOwaNe_HAG7IVU8yzrmxyPuszA3E7XLT8eiI
      - GITEA__security__PASSWORD_HASH_ALGO=pbkdf2
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__oauth2__JWT_SECRET=Uhx_2Vdw7edeIKNilxe6b8ChN_ftnDZYfk-GgXBoikY
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - GITEA__service__ENABLE_CAPTCHA=false
      - GITEA__service__NO_REPLY_ADDRESS=noreply.localhost
      - GITEA__APP_NAME=Rastion
      - GITEA__RUN_USER=papaflesas
    restart: always
    networks:
      - gitea-network
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db      

  db:
    image: docker.io/library/mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea-network
    volumes:
      - ./mysql:/var/lib/mysql


      