
networks:
  gitea-network:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 15.15.15.0/24  # Define a custom subnet

services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql-gitea-db:3306
      - GITEA__database__NAME=${MYSQL_DATABASE}
      - GITEA__database__USER=${MYSQL_USER}
      - GITEA__database__PASSWD=${MYSQL_PASSWORD}
      - GITEA__database__SSL_MODE=disable
      - GITEA__cors__ENABLED=true
      - GITEA__cors__ALLOW_ORIGIN=http://localhost:8080
      - GITEA__cors__ALLOW_CREDENTIALS=true
      - GITEA__cors__ALLOW_HEADERS=Authorization, Content-Type
      - GITEA__server__ROOT_URL=http://localhost:3000/
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__session__PROVIDER=file
      - GITEA__security__INTERNAL_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NDE3MDYzMDd9.UfJxCwucOwaNe_HAG7IVU8yzrmxyPuszA3E7XLT8eiI
      - GITEA__security__PASSWORD_HASH_ALGO=pbkdf2
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__oauth2__JWT_SECRET=Uhx_2Vdw7edeIKNilxe6b8ChN_ftnDZYfk-GgXBoikY
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=false
      - GITEA__service__ENABLE_CAPTCHA=false
      - GITEA__service__NO_REPLY_ADDRESS=noreply.localhost
      - GITEA__APP_NAME=Rastion
      - GITEA__RUN_USER=papaflesas
    restart: always
    networks:
      gitea-network:
        ipv4_address: 15.15.15.100
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mysql-gitea-db      

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${KNEX_DB}
      POSTGRES_USER: ${KNEX_USER}
      POSTGRES_PASSWORD: ${KNEX_PW}
    ports:
      - "5432:5432"
    networks:
      gitea-network:
        ipv4_address: 15.15.15.103
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql-gitea-db:
    image: docker.io/library/mysql:8
    restart: always
    container_name: mysql-gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      gitea-network:
        ipv4_address: 15.15.15.101
    volumes:
      - ./mysql:/var/lib/mysql

  backend:
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    container_name: backend-server
    working_dir: /app
    environment:
      KNEX_HOST: ${KNEX_HOST}
      KNEX_USER: ${KNEX_USER}
      KNEX_PW: ${KNEX_PW}
      KNEX_DB: ${KNEX_DB}
      GITEA_URL: 'http://15.15.15.100:3000'
      SECRET_TOKEN: ${SECRET_TOKEN}
      PLAYGROUND_NAMESPACE: ${PLAYGROUND_NAMESPACE:-playground}
      PLAYGROUND_IMAGE: ${PLAYGROUND_IMAGE:-registry.digitalocean.com/rastion/qubots-playground:latest}
    volumes:
      - ./backend-server:/app
      - /app/node_modules   # Avoid overwriting node_modules
    ports:
      - "4000:4000"
    networks:
      gitea-network:
        ipv4_address: 15.15.15.102
    restart: always
    depends_on:
      - server
      - postgres
    command: node server.js  # Command to run your Node.js app


volumes:
  pgdata:
      