version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    # allow Vite to proxy to your host-side API
    # on Linux/Mac/Win Docker 20.10+, host.docker.internal works out-of-the-box
    extra_hosts:
      - "host.docker.internal:host-gateway"